# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 1044

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8

# ENDPOINTS (AbstractEndpoint subclasses)
endpoints:
  enabled: true

# NEO4j
#neo4j:
#  username: neo4j
#  password: admin